version: '3.8'
services:
    app:
        build:
            context: ..
            dockerfile: ../Dockerfile
        image: ltms
        container_name: ltms-container
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: ltms-nginx-container
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: ltms-mysql-container
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: Root@1214.com
            MYSQL_DATABASE: ltms
            MYSQL_USER: ltms
            MYSQL_PASSWORD: ltms@1214.com
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
